services:
  tilemaker-server:
    build:
      context: "."
      dockerfile: "Dockerfile"
    container_name: "tilemaker-server"
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    volumes:
      - type: "bind"
        # Get your maps in!
        source: "./mymaps"
        target: "/mymaps"
      - type: "bind"
        # Export your config file into the container
        source: "./config.json"
        target: "/config.json"
