# MapGroup(
#     [
#         Map(
#             map_type="iqu",
#             bands=[
#                 Band(
#                     band_type="iqu_band",
#                     frequency='f090',
#                     layers=[
#                         Layer(
#                             layer_type="fits_layer",
#                             layer_id="I",
#                             provided_by="path/to/fitsfile.fits",
#                             hdu=0,
#                             index=0,
#                         )
#                     ]
#                 )
#             ]
#         )
#     ]
# )

# MapGroup(
#     [
#         Map(
#             map_type="compton_y",
#             bands=[
#                 Band(
#                     band_type="compton_band",
#                     layers=Layer(
#                         layer_type="fits_layer",
#                         layer_id="y",
#                         provided_by="path/to/fitsfile.fits"
#                     )
#                 )
#             ]
#         )
#     ]
# )
